### ISSUE TITLE
Implement input globbing

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/rFDP#100]
We should be able to find out what data products and components are available using the DPAPI - this is one of those things that Martin has probably got in his extended interface. The reason it matters is that we want to be able to say `human/disease/sars-cov-2/datasets/**` in the read block of a yaml file, and then read them all in in the code without knowing in advance what they are all called.

`*` is one level
`**` is recursive

**Comment by soniamitchell** [comment]
user-written config:
```yaml
read:
- data_product: real/data/**
```
should return working config:
```yaml
read:
- data_product: real/data/1
- data_product: real/data/2
- data_product: real/data/3
- data_product: real/data/4
- data_product: real/data/5
```

so that `find_data_products("real/data/**")` can read the working config and return a list of data products
