### ISSUE TITLE
Implement output globbing

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/rFDP#101]
We’d like to be able to write that we are going to output a bunch of files (maybe one for each input we have, but we’re using globbing on the inputs) so we write in the write block of the user `yaml my/output/datasets/**`, and fair run correctly identifies all of the existing entries in the registry that match that, but there will be potentially lots of new ones too. So does fair run need some way of communicating to the DPAPI in the working yaml what to do with those files when you write them - *e.g.* what namespace or what version number to use? If so, how does it do that?

**Comment by soniamitchell** [comment]
user-written config:
```yaml
write:
- data_product: real/data/**
  use:
    namespace: someone
    version: ${{CLI.MAJOR}}
```
should return working config
```yaml
write:
- data_product: real/data/1
  use:
    namespace: someone
    version: 0.1.0
- data_product: real/data/thing/1
  use:
    namespace: someone
    version: 0.1.0
- data_product: real/data/**
  use:
    namespace: someone
    version: 0.0.1
```
so that the next version of `real/data/thing/1` may be written or instead, a new
